### ISSUE TITLE
Improve `ImageList` status management

### ISSUE THREAD

**Issue by shuguang-lv** [HaohanWang/Robustar_implementation#117]
Currently, the image list view involves many image-related status, some of which are tightly coupled when updated. At the same time, there are different sources that could manipulate these status variables possibly in an unsynchronized way, which may also cause chaos to the status management as well as the testing. Therefore, some refactoring or improvements are required to reduce the status of this page and make them more intuitive. Maybe it is also a good idea to split this page into several self-contained components so that status can be better grouped by their functionalities.

**Suggestions are welcome for this issue!**

**Comment by PaulCCCCCCH** [comment]
Refactored in #111. Uses a global state instead of components' internal states to track current image, split, etc..
