### ISSUE TITLE
Problem with the library `python-magic-bin` 

### ISSUE THREAD

**Issue by PaulCCCCCCH** [HaohanWang/Robustar_implementation#55]
After the optimization done by @YuhaoZhang00, the backend is encoding images to base64 and send them to the frontend.

We introduced the library `python-magic` to get the meta data of the image and prepend that to the base64 string. For Windows, we need to install with `pip install python-magic-bin`, and for Linux, we need to install with `pip install python-magic`. The import statement will be the same in Python: `import magic`

Installing `python-magic-bin` on Linux gives "pip module not found". Installing `python-magic` and on Windows is OK, but will block when executing `import magic`.

**Comment by PaulCCCCCCH** [comment]
Instead of installing different packages based on OS, let's try to not rely on this library.

I'm looking into that.

**Comment by YuhaoZhang00** [comment]
I used `python-magic` library to get the MIME type of the file, which would work for (almost) all file types; but if we only allow certain image types as our dataset (e.g. `png`, `jpg`, `jpeg`, and such) (which is likely to be), we can manually work out the MIME type from its file name (e.g. `dog0.png` -> MIME type `image/png` , i.e. `image/` + `lower case of file suffix`)

**Comment by YuhaoZhang00** [comment]
https://www.iana.org/assignments/media-types/media-types.xhtml#image

Here is a list of official image MIME types

**Comment by PaulCCCCCCH** [comment]
Actually I found this useful. `https://stackoverflow.com/a/43588/11441741`
Basically there is a built-in library called `memetypes` that you don't need to install. I'm trying it out.

**Comment by YuhaoZhang00** [comment]
Yes this seems good.

**Comment by PaulCCCCCCH** [comment]
Resolved by #58
