### ISSUE TITLE
Frontend API services wrapper not handling reply code correctly

### ISSUE THREAD

**Issue by PaulCCCCCCH** [HaohanWang/Robustar_implementation#83]
After refactoring all frontend API services to be async, we are no longer using the error handling code below
```
const handleResult = (res, success, failed) => {
  if (successCode.includes(res.status)) {
    if (res.data.code == -1) {
      console.log(res.data.msg);
    } else {
      success(res);
    }
  } else {
    failed(res);
  }
};
```

As a result, frontend is not handling the errors correctly.

Two solutions here:
1. Wrap current frontend API service with a new handler
2. Change the backend to change the HTTP reply code instead of using our own error code in `data` field.

**Comment by shuguang-lv** [comment]
@PaulCCCCCCH I think it is better to change the HTTP status code sent by backend (i.e. using 4xx or 5xx properly). Frontend Axios APIs could then throw errors (which can be caught by try-catch block) accordingly when the status code is not 2xx.

**Comment by PaulCCCCCCH** [comment]
@shuguang-lv I've updated the backend to set the HTTP status code correctly in [this branch](https://github.com/PaulCCCCCCH/Robustar_implementation/tree/status-code).

**Comment by shuguang-lv** [comment]
@PaulCCCCCCH Frontend was updated accordingly in [this branch](https://github.com/PaulCCCCCCH/Robustar_implementation/tree/status-code).
