### ISSUE TITLE
Skip some files in pre-commit checks

### ISSUE THREAD

**Issue by PaulCCCCCCH** [HaohanWang/Robustar_implementation#88]
Style checking is taking too long. We can skip some of them. For example, we don't need to check for output files under `dist`.

**Comment by shuguang-lv** [comment]
Use [pre-commit](https://prettier.io/docs/en/precommit.html#option-3-pre-commithttpsgithubcompre-commitpre-commit) with prettier

**Comment by shuguang-lv** [comment]
Use prettier with [lint-staged](https://prettier.io/docs/en/precommit.html#option-1-lint-stagedhttpsgithubcomokonetlint-staged)
