### ISSUE TITLE
Improve `ImageEditor` page logic

### ISSUE THREAD

**Issue by PaulCCCCCCH** [HaohanWang/Robustar_implementation#94]
See `front-end/packages/robustar/views/EditImage.vue`.

The way `TUIImageEditor` loads an image is by reading an `imageUrl` from `sessionStorage` (see its `loadImageFromUrl` function). Thus, in the current implementation, when we want to load an image, we will first store an image URL in `sessionStorage`, then call `loadImageFromUrl`. We the URL "the URL to the image **to load**", or `U_L`.

At the same time, we need to maintain a separate url: "the URL to the image we are editing", or `U_E`. 
`U_L` and `U_E` are usually the same, e.g., we are editing a training image. 
However, they can be different. Examples:
- if we click `Auto Edit` when editing a training image `train/10`, it will load a proposed image (`U_L` points to `proposed/10`). When saving this image, we still need to pass `train/10` (saved in `U_E`) to the backend to let it know which image we wish to change.
- If we click `Load Edit` when editing a training image `train/10`, we need to have `U_L = annotated/5` and `U_E = train/10` (assume the 5th annotated image corresponds to the 10th training image). We cannot simply make `U_L = U_E = annotated/5` because when we click next, we expect to see image `train/10+1` instead of `annotated/5 + 1`.

Now, `U_L` is saved in `sessionStorage`, and `U_L` is saved as component fields `this.split` and this.image_url`. This is not a very intuitive design because we have two separate urls to maintain. I wonder if we can make this better, even if it involves some non-trivial changes on how `TUIImageEditor` loads an image. 

On potential solution: let `TUIImageEditor` take a base64 string for an image rather than an image URL, so that we only have one URL (`U_E`), which has nothing to do with what image is actually loaded at all.

**Comment by shuguang-lv** [comment]
Maybe we can use Vuex for better global state management in the future
