### ISSUE TITLE
Code quality review

### ISSUE THREAD

**Issue by PaulCCCCCCH** [HaohanWang/Robustar_implementation#96]
We have only started focusing on code quality over feature iteration speed recently. There are a few problems (some of them even inherited from the very first version of `Robustar`). It's time for us to clean them up. Here is an incomplete list of the things we need to do:

1. [ ] Remove dead code, e.g. `backend/modules/influence_module/main.py`. 
2. [ ] Remove outdated and useless comment.
3. [ ] Fix naming. Make sure we use snake case (e.g., `var_name`) for most cases except for types, classes and constants. Reference [here](https://peps.python.org/pep-0008/#prescriptive-naming-conventions)
4. [ ] Fix any non-intuitive code logic.

We should break down this issue into a few PRs to avoid too many changes in a single PR.

**Comment by YuhaoZhang00** [comment]
#### Non-intuitive response of `RResponse.ok()` when there's no data feedback

The parameters of `RResponse.ok()` method is `def ok(data, message='Success', code=0)`, which suggests that a success response is indicated by the message `Success` and code `0`. For responses with no data (e.g. `api_user_edit`, `api_delete_edit`, `api_clear_edit`), the `data` in the response should be empty. However, current responses for aforementioned ones are written as `return RResponse.ok("Success!")` (and in other places `return RResponse.ok("")`, `return RResponse.ok("success")`, ...), which is non-intuitive (how should the front-end use the returned data `Success!`?) and redundant (data and message both suggests a success).

A simple fix will be to set a default value of `None` for `data` in `RResponse.ok()`, i.e. `def ok(data=None, message='Success', code=0)`, and for APIs with no data return, simply use `RResponse.ok()`

\* Also, a HTTP response with status 200 already suggest a success, which seems to be another level of redundency.  There are other HTTP status maybe we can utilize to simplify / replace `RResponse.ok()`, for example `204 No Content`

**Comment by YuhaoZhang00** [comment]
#### Uniform formatting of back-end response data

e.g. currently
`get_image_list()` returns `[[image_path, ...], [image_data, ...]]`
`api_proposed_edit()` returns `{"path": image_path, "base64": image_data}`
